### PR TITLE
Glib: Bugfix: .Connect can produce race condition with access to marshall type map

### PR DESCRIPTION
**Pull request by atishnazir**
Writing an AutoPlugger in GStreamer (go-gst) using signals from components results in a tree of autoplugging from signal handlers.

 1. create pipeline of souphttp -> dashdmux
 2. dashdemux parses manifest and raises pad-added signals
 3. pad-added handler connects two typefind elements and connects to "have-type"
 4. typedfind raises "have-type".  Within handler connects a tsdemux element.
 5. tsdemux raises "pad-added" etc.

All these signals can fire in separate threads meaning we have concurrent access to marshalMap for complicated types such as Bins.

When this occurs the Go runtime raises the panic below, the fix puts a critical section around the marshalMap in all the related accessors.

```
fatal error: concurrent map writes

goroutine 50 [running, locked to thread]:
runtime.throw(0xc1b29d, 0x15)
	/usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc000394838 sp=0xc000394808 pc=0x47c992
runtime.mapassign_fast64(0xb70840, 0xc000020360, 0x7fdc140063e0, 0x5dd14b)
	/usr/lib/golang/src/runtime/map_fast64.go:176 +0x325 fp=0xc000394878 sp=0xc000394838 pc=0x457485
github.com/tinyzimmer/go-glib/glib.marshalMap.register(0xc000020360, 0xc000394930, 0x1, 0x1)
	/home/na/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.23/glib/gvalue.go:339 +0x73 fp=0xc0003948b8 sp=0xc000394878 pc=0x5e05d3
github.com/tinyzimmer/go-glib/glib.RegisterGValueMarshalers(...)
	/home/na/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.23/glib/gvalue.go:306
github.com/tinyzimmer/go-gst/gst.(*Element).Connect(0xc00030e208, 0xc12c64, 0x9, 0xb03960, 0xc00032e030, 0x0, 0x0, 0xf)
	/home/na/go/pkg/mod/github.com/tinyzimmer/go-gst@v0.2.27/gst/gst_element.go:174 +0x186 fp=0xc000394950 sp=0xc0003948b8 pc=0x629846

```

### CODE REVIEW

**Comment by tinyzimmer** [comment]
Yikes! Thanks for the PR. I'm traveling at the moment, but will try to find time to look it over later.

**Comment by atishnazir** [comment]
All good.  Nice work on this library, it feels really natural working with GStreamer in Go (trumps Vala which was my previous favourite).

**Comment by tinyzimmer** [comment]
Let me know what you think about the RWMutex, but other than that looks good

**Comment by atishnazir** [comment]
RWMutex is a better fit for how it's used, I'll tweak accordingly and update

**Comment by tinyzimmer** [comment]
LGTM - Will merge and then do a new tag on `go-gst` with the updated dep

**Comment by tinyzimmer** [comment]
v0.2.29 of go-gst has this fix

**Pull request merged**
